agent: 'claude --ide'
merge_strategy: rebase
nerdfont: false
theme: dark
mode: window

files:
  symlink:
    - .claude/settings.local.json

post_create:
  - mise trust

panes:
  - command: <agent>
    focus: true
  - split: horizontal
    size: 80
    command: nvim --cmd "let g:workmux=1"

status_icons:
  working: "🤖"
  waiting: "💬"
  done: "✅"
